<a href="https://colab.research.google.com/github/rogeriodelphi/trader_esportivo_analises/blob/main/FutPythonTrader_An%C3%A1lises_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importando as Bibliotecas

In [1]:

import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from google.colab import data_table
data_table.enable_dataframe_formatter()

## Coletando as planilhas das Ligas Principais

In [2]:
# Inglaterra 1
ENG1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E0.csv")
ENG1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/E0.csv")
ENG1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/E0.csv")
ENG1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/E0.csv")
ENG1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/E0.csv")
ENG1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/E0.csv")
ENG1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/E0.csv")
ENG1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/E0.csv")
ENG1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/E0.csv")
ENG1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/E0.csv")
ENG1 = [ENG1_01,ENG1_02,ENG1_03,ENG1_04,ENG1_05,ENG1_06,ENG1_07,ENG1_08,ENG1_09,ENG1_10]
ENG1 = pd.concat(ENG1)
ENG1['Liga'] = 'Inglaterra 1'

# Inglaterra 2
ENG2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E1.csv")
ENG2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/E1.csv")
ENG2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/E1.csv")
ENG2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/E1.csv")
ENG2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/E1.csv")
ENG2_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/E1.csv")
ENG2_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/E1.csv")
ENG2_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/E1.csv")
ENG2_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/E1.csv")
ENG2_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/E1.csv")
ENG2 = [ENG2_01,ENG2_02,ENG2_03,ENG2_04,ENG2_05,ENG2_06,ENG2_07,ENG2_08,ENG2_09,ENG2_10]
ENG2 = pd.concat(ENG2)
ENG2['Liga'] = 'Inglaterra 2'

# Escócia 1
SCO1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SC0.csv")
SCO1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SC0.csv")
SCO1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/SC0.csv")
#SCO1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/SC0.csv")
SCO1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/SC0.csv")
SCO1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/SC0.csv")
SCO1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/SC0.csv")
SCO1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/SC0.csv")
SCO1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/SC0.csv")
SCO1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/SC0.csv")
# SCO1 = [SCO1_01,SCO1_02,SCO1_03,SCO1_04,SCO1_05,SCO1_06,SCO1_07,SCO1_08,SCO1_09,SCO1_10]
SCO1 = [SCO1_01,SCO1_02,SCO1_03,SCO1_05,SCO1_06,SCO1_07,SCO1_08,SCO1_09,SCO1_10]
SCO1 = pd.concat(SCO1)
SCO1['Liga'] = 'Escócia 1'

# Alemanha 1
GER1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/D1.csv")
GER1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/D1.csv")
GER1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/D1.csv")
GER1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/D1.csv")
GER1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/D1.csv")
GER1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/D1.csv")
GER1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/D1.csv")
GER1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/D1.csv")
GER1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/D1.csv")
GER1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/D1.csv")
GER1 = [GER1_01,GER1_02,GER1_03,GER1_04,GER1_05,GER1_06,GER1_07,GER1_08,GER1_09,GER1_10]
GER1 = pd.concat(GER1)
GER1['Liga'] = 'Alemanha 1'

# Alemanha 2
GER2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/D2.csv")
GER2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/D2.csv")
GER2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/D2.csv")
GER2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/D2.csv")
GER2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/D2.csv")
GER2_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/D2.csv")
GER2_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/D2.csv")
GER2_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/D2.csv")
GER2_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/D2.csv")
GER2_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/D2.csv")
GER2 = [GER2_01,GER2_02,GER2_03,GER2_04,GER2_05,GER2_06,GER2_07,GER2_08,GER2_09,GER2_10]
GER2 = pd.concat(GER2)
GER2['Liga'] = 'Alemanha 2'

# Itália 1
ITA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I1.csv")
ITA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/I1.csv")
ITA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/I1.csv")
ITA1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/I1.csv")
ITA1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/I1.csv")
ITA1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/I1.csv")
ITA1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/I1.csv")
ITA1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/I1.csv")
ITA1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/I1.csv")
ITA1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/I1.csv")
ITA1 = [ITA1_01,ITA1_02,ITA1_03,ITA1_04,ITA1_05,ITA1_06,ITA1_07,ITA1_08,ITA1_09,ITA1_10]
ITA1 = pd.concat(ITA1)
ITA1['Liga'] = 'Itália 1'

# Itália 2
ITA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I2.csv")
ITA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/I2.csv")
ITA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/I2.csv")
# ITA2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/I2.csv")
ITA2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/I2.csv")
ITA2_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/I2.csv")
ITA2_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/I2.csv")
ITA2_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/I2.csv")
ITA2_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/I2.csv")
ITA2_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/I2.csv")
# ITA2 = [ITA2_01,ITA2_02,ITA2_03,ITA2_04,ITA2_05,ITA2_06,ITA2_07,ITA2_08,ITA2_09,ITA2_10]
ITA2 = [ITA2_01,ITA2_02,ITA2_03,ITA2_05,ITA2_06,ITA2_07,ITA2_08,ITA2_09,ITA2_10]
ITA2 = pd.concat(ITA2)
ITA2['Liga'] = 'Itália 2'

# Espanha 1
SPA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP1.csv")
SPA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SP1.csv")
SPA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/SP1.csv")
SPA1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/SP1.csv")
SPA1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/SP1.csv")
SPA1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/SP1.csv")
SPA1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/SP1.csv")
SPA1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/SP1.csv")
SPA1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/SP1.csv")
SPA1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/SP1.csv")
SPA1 = [SPA1_01,SPA1_02,SPA1_03,SPA1_04,SPA1_05,SPA1_06,SPA1_07,SPA1_08,SPA1_09,SPA1_10]
SPA1 = pd.concat(SPA1)
SPA1['Liga'] = 'Espanha 1'

# Espanha 2
SPA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP2.csv")
SPA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SP2.csv")
SPA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/SP2.csv")
SPA2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/SP2.csv")
SPA2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/SP2.csv")
SPA2_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/SP2.csv")
SPA2_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/SP2.csv")
SPA2_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/SP2.csv")
SPA2_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/SP2.csv")
SPA2_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/SP2.csv")
SPA2 = [SPA2_01,SPA2_02,SPA2_03,SPA2_04,SPA2_05,SPA2_06,SPA2_07,SPA2_08,SPA2_09,SPA2_10]
SPA2 = pd.concat(SPA2)
SPA2['Liga'] = 'Espanha 2'

# França 1
FRA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F1.csv")
FRA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/F1.csv")
FRA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/F1.csv")
FRA1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/F1.csv")
FRA1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/F1.csv")
FRA1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/F1.csv")
FRA1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/F1.csv")
FRA1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/F1.csv")
FRA1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/F1.csv")
FRA1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/F1.csv")
FRA1 = [FRA1_01,FRA1_02,FRA1_03,FRA1_04,FRA1_05,FRA1_06,FRA1_07,FRA1_08,FRA1_09,FRA1_10]
FRA1 = pd.concat(FRA1)
FRA1['Liga'] = 'França 1'

# França 2
FRA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F2.csv")
FRA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/F2.csv")
FRA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/F2.csv")
FRA2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/F2.csv")
FRA2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/F2.csv")
FRA2_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/F2.csv")
FRA2_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/F2.csv")
FRA2_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/F2.csv")
FRA2_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/F2.csv")
FRA2_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/F2.csv")
FRA2 = [FRA2_01,FRA2_02,FRA2_03,FRA2_04,FRA2_05,FRA2_06,FRA2_07,FRA2_08,FRA2_09,FRA2_10]
FRA2 = pd.concat(FRA2)
FRA2['Liga'] = 'França 2'

# Holanda 1
NET1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/N1.csv")
NET1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/N1.csv")
NET1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/N1.csv")
NET1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/N1.csv")
NET1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/N1.csv")
NET1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/N1.csv")
NET1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/N1.csv")
NET1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/N1.csv")
NET1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/N1.csv")
NET1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/N1.csv")
NET1 = [NET1_01,NET1_02,NET1_03,NET1_04,NET1_05,NET1_06,NET1_07,NET1_08,NET1_09,NET1_10]
NET1 = pd.concat(NET1)
NET1['Liga'] = 'Holanda 1'

# Bélgica 1
BEL1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/B1.csv")
BEL1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/B1.csv")
BEL1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/B1.csv")
BEL1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/B1.csv")
BEL1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/B1.csv")
BEL1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/B1.csv")
BEL1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/B1.csv")
BEL1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/B1.csv")
BEL1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/B1.csv")
BEL1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/B1.csv")
BEL1 = [BEL1_01,BEL1_02,BEL1_03,BEL1_04,BEL1_05,BEL1_06,BEL1_07,BEL1_08,BEL1_09,BEL1_10]
BEL1 = pd.concat(BEL1)
BEL1['Liga'] = 'Bélgica 1'

# Portugal 1
POR1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/P1.csv")
POR1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/P1.csv")
POR1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/P1.csv")
POR1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/P1.csv")
POR1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/P1.csv")
POR1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/P1.csv")
POR1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/P1.csv")
POR1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/P1.csv")
POR1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/P1.csv")
POR1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/P1.csv")
POR1 = [POR1_01,POR1_02,POR1_03,POR1_04,POR1_05,POR1_06,POR1_07,POR1_08,POR1_09,POR1_10]
POR1 = pd.concat(POR1)
POR1['Liga'] = 'Portugal 1'

# Turquia 1
TUR1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/T1.csv")
TUR1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/T1.csv")
TUR1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/T1.csv")
TUR1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/T1.csv")
TUR1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/T1.csv")
TUR1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/T1.csv")
TUR1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/T1.csv")
TUR1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/T1.csv")
TUR1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/T1.csv")
TUR1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/T1.csv")
TUR1 = [TUR1_01,TUR1_02,TUR1_03,TUR1_04,TUR1_05,TUR1_06,TUR1_07,TUR1_08,TUR1_09,TUR1_10]
TUR1 = pd.concat(TUR1)
TUR1['Liga'] = 'Turquia 1'

# Grécia 1
GRE1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/G1.csv")
GRE1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/G1.csv")
GRE1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/G1.csv")
GRE1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/G1.csv")
GRE1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/G1.csv")
GRE1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/G1.csv")
GRE1_07 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1516/G1.csv")
GRE1_08 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1415/G1.csv")
GRE1_09 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1314/G1.csv")
GRE1_10 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1213/G1.csv")
GRE1 = [GRE1_01,GRE1_02,GRE1_03,GRE1_04,GRE1_05,GRE1_06,GRE1_07,GRE1_08,GRE1_09,GRE1_10]
GRE1 = pd.concat(GRE1)
GRE1['Liga'] = 'Grécia 1'

## Concatenando as Planilhas

In [5]:
df = [ENG1, ENG2, SCO1, GER1, GER2, ITA1, ITA2, SPA1, SPA2, FRA1, FRA2, NET1, BEL1, POR1, TUR1, GRE1]
df = pd.concat(df)
df

Warning: total number of rows (55295) exceeds max_rows (20000). Falling back to pandas display.

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,GBH,GBD,GBA,BSH,BSD,BSA,Liga,HFKC,AFKC,Unnamed: 105
0,E0,13/08/2021,20:00,Brentford,Arsenal,2.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Inglaterra 1,NaN,NaN,NaN
1,E0,14/08/2021,12:30,Man United,Leeds,5.0,1.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Inglaterra 1,NaN,NaN,NaN
2,E0,14/08/2021,15:00,Burnley,Brighton,1.0,2.0,A,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Inglaterra 1,NaN,NaN,NaN
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3.0,0.0,H,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Inglaterra 1,NaN,NaN,NaN
4,E0,14/08/2021,15:00,Everton,Southampton,3.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Inglaterra 1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,G1,21/04/13,NaN,Panthrakikos,Kerkyra,2.0,1.0,H,1.0,0.0,...,1.20,6.25,13.00,NaN,NaN,NaN,Grécia 1,NaN,NaN,NaN
237,G1,21/04/13,NaN,PAOK,Giannina,2.0,0.0,H,0.0,0.0,...,1.50,3.80,7.25,NaN,NaN,NaN,Grécia 1,NaN,NaN,NaN
238,G1,21/04/13,NaN,Platanias,Levadeiakos,2.0,0.0,H,1.0,0.0,...,1.70,3.50,5.00,NaN,NaN,NaN,Grécia 1,NaN,NaN,NaN
239,G1,21/04/13,NaN,Xanthi,Aris,0.0,0.0,D,0.0,0.0,...,6.75,3.90,1.50,NaN,NaN,NaN,Grécia 1,NaN,NaN,NaN
240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Grécia 1,NaN,NaN,NaN